project_id = "gducdbslxhugyqxbfkic"

[functions.set-worker-pin]
verify_jwt = false

[functions.verify-worker-pin]
verify_jwt = false

[functions.reset-worker-pin]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false